### ISSUE TITLE
Offline Controller.

### ISSUE THREAD

**Issue by juliolitwin** [ESCdeGmbH/chatbot-framework#2]
Yo,

I saw you started to developer the offline controller but you developed some script too for emulate the directline, but I'm looking something like offline controller, just send the conversationId and the WS recover the conversation and process the message without the azure or something else. How it's working it for now? My goal for now it's just to use postman and send some post with conversionId + text, it's possible? 

Cheers.

**Comment by Hossiphi** [comment]
Hi,

we're sorry we didn't get back to you sooner.

As you already have mentioned, we're emulating a directline connection. You could also do this by using Postman:

1) Sending a message to the bot: 
Take a look at the function [SendMessageToBot](https://github.com/dfuchss/Offline-MS-Bot-Connector/blob/master/script.js#L218). There you can find the necessary payload for the post request to "/api/messages". As directline needs a service url as endpoint for message sending of the bot, you'll need some back end for that. This back end is provided by the [OfflineController](https://github.com/ESCdeGmbH/chatbot-framework/blob/master/Controller/OfflineController.cs), where we've implemented a simple queuing/ polling mechanism. 

2) Receiving a message: 
As the directline protocol does not support returning the actual answer of the bot directly, you have to implement some back end or use some queuing/ polling  mechanisms. We've decided to put all the stuff in our framework. You can simply use Postman for this purpose. Just send a post request to "/v3/conversations/{conversationId}/poll" after you've sent a message. You can find the back end implementation of this in the [OfflineController](https://github.com/ESCdeGmbH/chatbot-framework/blob/master/Controller/OfflineController.cs).

Feel free to contact us again, if anything is unclear.

Best regards!

**Comment by Hossiphi** [comment]
Closed due to no response.
If you have further questions feel free to ask us.
